#! /usr/bin/env python
import sys

def main():
 t = input()
 while t > 0:
  inp = raw_input().split()
  amount = int(inp[0])
  acc_balance = float(inp[1])
  if amount % 5 == 0:
   total_debit = float(amount + 0.50)
   if total_debit > acc_balance:
    print "%.2f" % acc_balance
   else:
    print "%.2f" % (acc_balance - total_debit)
  else:
   print "%.2f" % acc_balance
  t -= 1
 return 0

if __name__ == '__main__':
 sys.exit(main())
