#! /usr/bin/env python
t = int(raw_input().strip())
while t > 0:
 try:
  inp = raw_input().strip().split()
  amount = int(inp[0].strip())
  acc_balance = float(inp[1].strip())
  if amount % 5 == 0:
   total_debit = float(amount + 0.50)
   if total_debit > acc_balance:
    print ("%.2f") % (acc_balance)
   else:
    print ("%.2f") % (acc_balance - total_debit)
  else:
   print ("%.2f") % (acc_balance)
 except Exception as e:
  print e
 t -= 1

